import streamlit as st

# Streamlit page setup
st.set_page_config(page_title="AI Text Detector", page_icon="🤖", layout="centered")

st.title("AIDENTIFY - AI Text Detector")
st.markdown("Welcome! Paste a sentence or paragraph below and find out if it was **AI-generated** or **Human-written**.")

# Large input area
user_input = st.text_area("Input your text here:", height=200, placeholder="Type or paste your text...")

# Detection logic triggers on button click
if st.button("SCAN") and user_input.strip():
    # ====== Begin original code block ======

    import math

    data = [
    #Human:
    ("This text was generated by an AI model.", 0),
    ("The AI-generated content is becoming more advanced.", 0),
    ("Machine learning models can generate realistic text.", 0),
    ("AI-generated text is often indistinguishable from human writing.", 0),
    ("In the course of this life I have had a great many encounters with a great many people who have been concerned with matters of consequence.", 0),
("If one gets lost in the night, such knowledge is valuable.", 0),
("Remember, I had crashed in the desert a thousand miles from any inhabited region.", 0),
("When a mystery is too overpowering, one dare not disobey.", 0),
("But I had never drawn a sheep.", 0),
("So I drew for him one of the two pictures I had drawn so often. I", 0),
("My friend smiled gently and indulgently.", 0),
("So then I did my drawing over once more.", 0),
("But it was rejected too, just like the others.", 0),
("And I threw out an explanation with it.", 0),
("He bent his head over the drawing", 0),
("And he sank into a reverie, which lasted a long time.", 0),
("You can imagine how my curiosity was aroused by this half-confidence about the others", 0),
("But he was in Turkish costume, and so nobody would believe what he said.", 0),
("One must not hold it against them.", 0),
("To those who understand life, that would have given a much greater air of truth to my story.", 0),
("For I do not want any one to read my book carelessly", 0),
("Six years have already passed since my friend went away from me, with his sheep.", 0),
("It is for that purpose, again, that I have bought a box of paints and some pencils.", 0),
("But I am not at all sure of success.", 0),
("And I feel some doubts about the color of his costume.", 0),
("He thought, perhaps, that I was like himself.", 0),
("Perhaps I am a little like the grown-ups.", 0),
("He thought, perhaps, that I was like himself. ", 0),
("My friend never explained anything to me.", 0),
("This time, once more, I had the sheep to thank for it.", 0),
("The idea of the herd of elephants made the little prince laugh.", 0),
("That would be very useful to them if they were to travel some day.", 0),
("But with the others I have not been successful", 0),
(" I was carried beyond myself by the inspiring force of urgent necessity.", 0),
("At first you seemed to be very much surprised.", 0),
(". And then you laughed to yourself.", 0),
("Everybody knows that when it is noon in the United States the sun is setting over France.", 0),
("But the little prince made no reply", 0),
("At that moment I was very busy trying to unscrew a bolt that had got stuck in my engine", 0),
("And I had so little drinking-water left that I had to fear for the worst.", 0),
("The little prince never let go of a question, once he had asked it.", 0),
("There was a moment of complete silence.", 0),
("Flowers are weak creatures.", 0),
("That made me a little ashamed.", 0),
    ("He tossed his golden curls in the breeze.", 0),
    ("He has never smelled a flower", 0),
    ("He has never done anything in his life but add up figures.", 0),
    ("The little prince was now white with rage.", 0),
    ("He could not say anything more.", 0),
    ("His words were choked by sobbing.", 0),
    ("I had let my tools drop from my hands", 0),
    ("I took him in my arms, and rocked him.", 0),
    ("I did not know what to say to him.", 0),
    ("I did not know how I could reach him.", 0),
    ("I soon learned to know this flower better.", 0),
    ("She chose her colors with the greatest care.", 0),
    ("She did not wish to go out into the world all rumpled, like the field poppies.", 0),
    ("But she interrupted herself at that point.", 0),
    ("She had come in the form of a seed.", 0),
    ("She cast her fragrance and her radiance over me.", 0),
    ("He carefully cleaned out his active volcanoes.", 0),
    ("On our earth we are obviously much too small to clean out our volcanoes.", 0),
    ("He was surprised by this absence of reproaches.", 0),
    ("For she did not want him to see her crying.", 0),
    ("The first of them was inhabited by a king.", 0),
    ("He did not know how the world is simplified for kings.", 0),
    ("It is years since I have seen anyone yawning.", 0),
    ("He sputtered a little, and seemed vexed.", 0),
    ("For what the king fundamentally insisted upon was that his authority should be respected.", 0),
    ("The king hastened to assure him.", 0),
    ("The second planet was inhabited by a conceited man.", 0),
    ("The little prince clapped his hands.", 0),
    ("The conceited man raised his hat in a modest salute.", 0),
    ("The conceited man again raised his hat in salute.", 0),
    ("After five minutes of this exercise the little prince grew tired of the game's monotony.", 0),
    ("But the conceited man did not hear him", 0),
    ("Conceited people never hear anything but praise.", 0),
    ("The next planet was inhabited by a tippler.", 0),
    ("And the little prince went away, puzzled.", 0),
    ("The fourth planet belonged to a businessman.", 0),
    ("The businessman raised his head.", 0),
    ("Nevertheless, he still had some more questions.", 0),
    ("The little prince was still not satisfied.", 0),
    ("The businessman opened his mouth, but he found nothing to say in answer.", 0),
    ("There was just enough room on it for a street lamp and a lamplighter.", 0),
    ("For it is possible for a man to be faithful and lazy at the same time.", 0),
    ("The sixth planet was ten times larger than the last one", 0),
    ("He does not leave his desk.", 0),
    ("Because an explorer who told lies would bring disaster on the books of the geographer.", 0),
    ("Because intoxicated men see double.", 0),
    ("That would be too complicated.", 0),
    ("The geographer was suddenly stirred to excitement.", 0),
    ("And, having opened his big register, the geographer sharpened his pencil.", 0),
    ("Two volcanoes are active and the other is extinct.", 0),
    ("And the little prince went away, thinking of his flower.", 0),
    ("So then the seventh planet was the Earth.", 0),
    ("Seen from a slight distance, that would make a splendid spectacle.", 0),
    (". Having set their lamps alight, these would go off to sleep.", 0),
    ("It would be magnificent.", 0),
    ("They adore figures, and that will please them.", 0),
    ("They fancy themselves as important as the baobabs.", 0),
    ("The grown-ups, to be sure, will not believe you when you tell them that.", 0),
    ("None of them noticed a large tawny owl flutter past the window.", 0),
    ("Mr Dursley blinked and stared at the cat.", 0),
    ("In fact, it was nearly midnight before the cat moved at all.", 0),
    ("This man's name was Albus Dumbledore.", 0),
    ("The nearest street lamp went out with a little pop.", 0),
    ("He couldn't kill that little boy.", 0),
    ("You couldn't find two people who are less like us.", 0),
    ("He was almost twice as tall as a normal man and at least five times as wide.", 0),
    ("In his vast, muscular arms he was holding a bundle of blankets.", 0),
    ("Inside, just visible, was a baby boy, fast asleep.", 0),
    ("Dumbledore turned and walked back down the street.", 0),
    ("He could just see the bundle of blankets on the step of number four", 0),
    ("His aunt was back outside the door.", 0),
    ("I want you to look after the bacon.", 0),
    ("It was a very sunny Saturday and the zoo was crowded with families.", 0),
    ("Dudley quickly found the largest snake in the place.", 0),
    ("He shuffled away.", 0),
    ("The snake jabbed its tail at a little sign next to the glass.", 0),
    ("There were no photographs of them in the house.", 0),
    ("He couldn't remember his parents at all.", 0),
    ("They also carried knobbly sticks, used for hitting each other while the teachers weren't looking.", 0),
    ("This was supposed to be good training for later life.", 0),
    ("He chuckled at his own joke.", 0),
    ("He sat down on the bed and stared around him.", 0),
    ("Other shelves were full of books.", 0),
    ("They were the only things in the room that looked as though they'd never been touched.", 0),
    ("Next morning at breakfast, everyone was rather quiet.", 0),
    ("The repaired alarm clock rang at six o’clock the next morning.", 0),
    ("Uncle Vernon stayed at home again.", 0),
    ("They didn't stop to eat or drink all day.", 0),
    ("He'd never had such a bad day in his life.", 0),
    ("Exactly what he was looking for, none of them knew.", 0),
    ("I want to stay somewhere with a television.", 0),
    ("It was very cold outside the car.", 0),
    ("It was freezing in the boat.", 0),
    ("There were only two rooms.", 0),
    ("He was in a very good mood.", 0),
    ("As night fell, the promised storm blew up around them.", 0),
    ("Someone was outside, knocking to come in.", 0),
    ("He was holding a rifle in his hands.", 0),
    ("A giant of a man was standing in the doorway.", 0),
    ("Uncle Vernon made a funny rasping noise.", 0),
    ("He held out an enormous hand and shook Harry's whole arm.", 0),
    ("The giant took a gulp of tea and wiped his mouth with the back of his hand.", 0),
    ("Taking him to buy his things tomorrow.", 0),
    ("She stopped to draw a deep breath and then went ranting on.", 0),
    ("It seemed she had been wanting to say all this for years.", 0),
    ("Dunno if he had enough human left in him to die", 0),
    ("Although he could tell it was daylight, he kept his eyes shut tight.", 0),
    ("There was suddenly a loud tapping noise.", 0),
    ("He went straight to the window and jerked it open.", 0),
    ("And the people have no imagination", 0),
    ("He was standing before a garden, all a-bloom with roses.", 0),
    ("The little prince gazed at them.", 0),
    ("They all looked like his flower.", 0),
    ("And he was overcome with sadness.", 0),
    ("And he lay down in the grass and cried.", 0),
    ("It was then that the fox appeared.", 0),
    ("The fox gazed at the little prince, for a long time.", 0),
    ("The little prince went away, to look again at the roses.", 0),
    ("And the roses were very much embarrassed.", 0),
    ("And a second brilliantly lighted express thundered by, in the opposite direction.", 0),
    ("This was a merchant who sold pills that had been invented to quench thirst.", 0),

#AI Generated:
    ("This is a human-written sentence.", 1),
    ("I enjoy reading books and writing stories.", 1),
    ("Natural language processing is a fascinating field.", 1),
    ("I love spending time with my family and friends.", 1),
    ("She enjoys reading books on rainy days.", 1),
    ("He loves playing chess in the evening.", 1),
    ("They traveled to Paris for their honeymoon.", 1),
    ("I always drink coffee in the morning.", 1),
    ("She dances to her favorite songs at home.", 1),
    ("We watched a movie last night.", 1),
    ("The children are playing in the park.", 1),
    ("My dog loves to chase after the ball.", 1),
    ("The ocean waves crashed against the shore.", 1),
    ("He enjoys painting landscapes in his free time.", 1),
    ("We visited the museum yesterday.", 1),
    ("She always wears her favorite blue dress.", 1),
    ("The rain is falling softly outside.", 1),
    ("They had a wonderful dinner at a restaurant.", 1),
    ("I prefer reading books to watching movies.", 1),
    ("The flowers in the garden are blooming beautifully.", 1),
    ("He played the guitar at the concert.", 1),
    ("We went hiking in the mountains last weekend.", 1),
    ("The cake was delicious and freshly baked.", 1),
    ("She smiled as she saw the rainbow in the sky.", 1),
    ("They celebrated their anniversary at a fancy hotel.", 1),
    ("I finished my homework early today.", 1),
    ("He bought a new car last week.", 1),
    ("I love watching the sunset by the beach.", 1),
    ("She helped me with my project last night.", 1),
    ("The city lights looked beautiful from the rooftop.", 1),
    ("We went to a concert last Friday.", 1),
    ("She baked a pie for Thanksgiving.", 1),
    ("He read the newspaper while drinking his coffee.", 1),
    ("I like to take long walks in the evening.", 1),
    ("The cat sat on the windowsill, watching the birds.", 1),
    ("She went shopping for groceries this morning.", 1),
    ("They visited their grandparents over the weekend.", 1),
    ("We had a picnic in the park yesterday.", 1),
    ("The sky turned orange as the sun set.", 1),
    ("She loves gardening and grows her own vegetables.", 1),
    ("I found a beautiful seashell on the beach.", 1),
    ("We met some old friends at the coffee shop.", 1),
    ("She finished reading her book in one sitting.", 1),
    ("The bird sang a cheerful song from the tree.", 1),
    ("They decided to take a road trip across the country.", 1),
    ("I like to take photos of interesting clouds.", 1),
    ("She wore a red scarf to keep warm.", 1),
    ("He spent the afternoon working on his car.", 1),
    ("The stars were shining brightly in the night sky.", 1),
    ("We enjoyed a quiet evening by the fireplace.", 1),
    ("The ice cream truck passed by the street.", 1),
    ("She loves to write poetry in her journal.", 1),
    ("He's always telling funny jokes to make us laugh.", 1),
    ("I walked through the forest and admired the trees.", 1),
    ("They celebrated Christmas with their family.", 1),
    ("The wind whispered through the tall grass.", 1),
    ("She made a delicious pasta for dinner.", 1),
    ("I bought a new pair of shoes today.", 1),
    ("He enjoys playing soccer with his friends.", 1),
    ("We spent the day exploring a new city.", 1),
    ("She sang her favorite song at karaoke.", 1),
    ("The candles flickered in the dark room.", 1),
    ("He painted a portrait of his mother.", 1),
    ("I took a nap in the afternoon after a long day.", 1),
    ("The mountains were covered in snow.", 1),
    ("She decorated her house with beautiful flowers.", 1),
    ("We saw a shooting star while camping.", 1),
    ("He enjoyed a cup of tea in the morning.", 1),
    ("The sound of the rain was very soothing.", 1),
    ("She took a stroll along the beach in the evening.", 1),
    ("We ate dinner at a cozy little bistro.", 1),
    ("The smell of fresh bread filled the air.", 1),
    ("She painted a beautiful sunset on canvas.", 1),
    ("He likes to read mystery novels before bed.", 1),
    ("We took a boat ride across the lake.", 1),
    ("The treehouse was our favorite childhood spot.", 1),
    ("See watched the clouds drift by from the porch.", 1),
    ("I enjoyed a hot cup of cocoa by the fire.", 1),
    ("They had a barbecue in the backyard.", 1),
    ("The train ride was scenic and relaxing.", 1),
    ("He made a toast to celebrate their success.", 1),
    ("We built a sandcastle on the beach.", 1),
    ("She loves listening to classical music in the evening.", 1),
    ("The puppy chased after its tail in circles.", 1),
    ("I found a quiet spot to read my book.", 1),
    ("She went for a jog in the park this morning.", 1),
    ("We watched a beautiful sunrise from the balcony.", 1),
    ("The coffee smelled so good in the morning.", 1),
    ("She enjoys knitting scarves during the winter.", 1),
    ("He worked late into the night on his project.", 1),
    ("We spent the afternoon at the zoo.", 1),
    ("She went to a pottery class last weekend.", 1),
    ("He played video games with his friends online.", 1),
    ("The house was decorated with colorful lights.", 1),
    ("I spent the morning cleaning the house.", 1),
    ("She took a break to relax in the hammock.", 1),
    ("They went to the mountains for a weekend getaway.", 1),
    ("I met a stranger who was kind and helpful.", 1),
    ("The breeze was cool and refreshing in the evening.", 1),
    ("She wore a yellow dress to the party.", 1),
    ("We enjoyed some fresh fruit for breakfast.", 1),
    ("The sound of the ocean was calming and peaceful.", 1),
    ("He visited the art gallery for inspiration.", 1),
    ("She made a scrapbook of her favorite memories.", 1),
    ("We went ice skating on the frozen lake.", 1),
    ("The flowers in the garden smelled sweet and fragrant.", 1),
    ("He enjoys writing stories in his free time.", 1),
    ("They enjoyed a relaxing afternoon at the spa.", 1),
    ("I took a photograph of the sunset on my phone.", 1),
    ("She baked a loaf of banana bread this morning.", 1),
    ("We saw a deer while walking through the forest.", 1),
    ("The weather was perfect for a picnic in the park.", 1),
    ("I love listening to rain sounds while I sleep.", 1),
    ("She loved the smell of fresh flowers in her room.", 1),
    ("We visited a historical site during our trip.", 1),
    ("He surprised her with a beautiful bouquet of flowers.", 1),
    ("The sound of the guitar echoed through the room.", 1),
    ("We played board games all afternoon.", 1),
    ("She enjoyed a peaceful moment by the lake.", 1),
    ("I tried a new recipe for dinner tonight.", 1),
    ("He bought a new guitar and started learning to play.", 1),
    ("We went camping and made s'mores around the fire.", 1),
    ("The birds were chirping early in the morning.", 1),
    ("She painted a mural on the wall of her room.", 1),
    ("I love walking through the woods in autumn.", 1),
    ("We explored an old castle during our vacation.", 1),
    ("The puppy fell asleep in my lap.", 1),
    ("She enjoys visiting new cafes around the city.", 1),
    ("We went bowling with some friends last weekend.", 1),
    ("He spent the day at the beach, reading a book.", 1),
    ("I made a cup of herbal tea to relax.", 1),
    ("She took a picture of the sunset with her camera.", 1),
    ("We enjoyed a delicious lunch at a local diner.", 1),
    ("He loves collecting old coins from different countries.", 1),
    ("The stars were so bright on the clear night.", 1),
    ("I spent the evening working on a puzzle.", 1),
    ("She wore a cozy sweater to keep warm.", 1),
    ("They went to a festival to enjoy the food and music.", 1),
    ("We went for a bike ride through the countryside.", 1),
    ("I like to sit by the window and watch the rain.", 1),
    ("She loves baking cakes for her friends and family.", 1),
    ("We danced to our favorite songs at the party.", 1),
    ("He took a photo of the full moon last night.", 1),
    ("I visited the bookstore to find a new novel.", 1),
    ("She made a homemade pizza for dinner.", 1),
    ("They went to the lake to enjoy some time outdoors.", 1),
    ("We saw a beautiful butterfly in the garden.", 1),
    ("She went for a run in the morning to stay fit.", 1),
    ("I enjoy having a cup of hot chocolate on cold days.", 1),
    ("He practiced his piano skills every evening.", 1),
    ("The autumn leaves turned golden and fell to the ground.", 1),
    ("We had a bonfire by the lake during our camping trip.", 1),
    ("She loves to explore new hiking trails.", 1),
    ("I spent the afternoon painting with watercolors.", 1),
    ("We watched a movie marathon on a rainy day.", 1),
    ("She took a yoga class to relieve stress.", 1),
    ("I spent the weekend organizing my closet.", 1),
    ("We had a barbecue in the backyard with friends.", 1),
    ("She loves to collect postcards from her travels.", 1),
    ("I spent the evening listening to music and relaxing.", 1),
    ("We visited the botanical garden to see the flowers.", 1),
    ("He played his favorite song on the piano.", 1),
    ("She spent the day volunteering at the animal shelter.", 1),
    ("We went to a new restaurant for dinner.", 1),
    ("I took a walk in the park to clear my mind.", 1),
    ("The candles created a warm, cozy atmosphere in the room.",
]

   # Separate text and labels
texts, labels = zip(*data)

# Step 2: Preprocess the Text
def preprocess(text):
    # Convert to lowercase and remove non-alphabetic characters
    text = text.lower()
    text = "".join(char for char in text if char.isalpha() or char.isspace())
    return text

# Tokenize the text into words
def tokenize(text):
    return text.split()

# Create a vocabulary from the dataset
vocab = set()
for text in texts:
    tokens = tokenize(preprocess(text))
    vocab.update(tokens)

# Convert the vocabulary to a list of words
vocab = list(vocab)

# Step 3: Convert Text to Numerical Features (Bag-of-Words)
def text_to_vector(text):
    vector = [0] * len(vocab)
    tokens = tokenize(preprocess(text))
    for token in tokens:
        if token in vocab:
            vector[vocab.index(token)] += 1
    return vector

# Convert all texts to feature vectors
X = [text_to_vector(text) for text in texts]
y = list(labels)

# Step 4: Split the Data into Training and Testing Sets
def train_test_split(X, y, test_size=0.25):
    split_index = int(len(X) * (1 - test_size))
    X_train, X_test = X[:split_index], X[split_index:]
    y_train, y_test = y[:split_index], y[split_index:]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Step 5: Implement a Naive Bayes Classifier
class NaiveBayesClassifier:
    def __init__(self):
        self.class_probs = {}
        self.feature_probs = {}

    def fit(self, X, y):
        n_samples = len(X)
        n_features = len(X[0])
        classes = set(y)

        # Calculate class probabilities
        for c in classes:
            self.class_probs[c] = sum(1 for label in y if label == c) / n_samples

        # Calculate feature probabilities
        for c in classes:
            self.feature_probs[c] = [0] * n_features
            class_samples = [X[i] for i in range(n_samples) if y[i] == c]
            for feature_index in range(n_features):
                feature_count = sum(sample[feature_index] for sample in class_samples)
                self.feature_probs[c][feature_index] = (feature_count + 1) / (len(class_samples) + n_features)

    def predict(self, X):
        predictions = []
        for sample in X:
            max_prob = -1
            best_class = -1
            for c in self.class_probs:
                prob = self.class_probs[c]
                for feature_index in range(len(sample)):
                    if sample[feature_index] > 0:
                        prob *= self.feature_probs[c][feature_index]
                if prob > max_prob:
                    max_prob = prob
                    best_class = c
            predictions.append(best_class)
        return predictions
    
    def predict_proba(self, X):
        probabilities = []
        for sample in X:
            class_probs = {}
            total_prob = 0
            for c in self.class_probs:
                prob = self.class_probs[c]
                for feature_index in range(len(sample)):
                    if sample[feature_index] > 0:
                        prob *= self.feature_probs[c][feature_index]
                class_probs[c] = prob
                total_prob += prob
            
            # Normalize probabilities
            for c in class_probs:
                class_probs[c] = class_probs[c] / total_prob
            probabilities.append(class_probs)
        return probabilities

# Train 
classifier = NaiveBayesClassifier()
classifier.fit(X_train, y_train)

# Step 6: model eval
y_pred = classifier.predict(X_test)

# Calculate accuracy
accuracy = sum(1 for i in range(len(y_test)) if y_test[i] == y_pred[i]) / len(y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Step 7: predict
def detect_ai_text(text):
    vector = text_to_vector(text)
    prediction = classifier.predict([vector])[0]
    proba = classifier.predict_proba([vector])[0]
    confidence = proba[prediction] * 100
    return ("AI-generated" if prediction == 1 else "Human-written", confidence)

# Add user input functionality
if __name__ == "__main__":
    print("AI Text Detector")
    print("Bla-bla type something here")
    print("Type 'quit' to exit\n")
    
    while True:
        user_input = input("Enter a sentence: ")
        if user_input.lower() == 'quit':
            break
        result, confidence = detect_ai_text(user_input)
        print(f"Prediction: {result} (Confidence: {confidence:.2f}%)\n")
    
    print("Thank you for using our program :) ")
